### ISSUE TITLE
How to obtain the depth of the Laval HDRI dataset

### ISSUE THREAD

**Issue by hxwork** [WinterCyan/Gardner2019#2]
Hi,

Thanks for releasing this re-implementation of the original paper. The paper uses EnvyDepth to obtain per-pixel depth estimates, and I noticed a directory named "HDR_DepthFile" in your codes. I would like to ask about how to obtain the depth information. Is there any method, code, or download link?

**Comment by WinterCyan** [comment]
I sent an email to ask one of the authors of [Gardner2019] for the depth annotation dataset, but the download link is expired now. You may ask the authors for a new valid link.

**Comment by hxwork** [comment]
Thanks for your rapid reply. I will try it.
